del applies.h
del applies_table.c
del comptest.c
del comptest.exe
del comptest.obj
del configure.h
del efun_defs.c
del efun_protos.h
del efunctions.h
del func_spec.cpp
del grammar.c
del grammar.h
del grammar.y
del make_func.c
del malloc.c
del opc.h
del opcodes.h
del option_defs.c
del options_incl.h
del trash_me.bat
del trash_me.err
del PACKAGES\packages