//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mudos.rc
//
#define IDREG                           3
#define IDUNREG                         4
#define IDS_MUDOS_DESC                  101
#define IDS_FUNCTION_DESC               102
#define IDI_SVR                         102
#define IDS_VALUE_DESC                  103
#define IDS_MOBJECT_DESC                105
#define IDD_SETUP_DLG                   105
#define IDS_MPROGRAM_DESC               106
#define IDS_MVALUE_DESC                 107
#define IDS_MFUNCTION_DESC              108
#define IDS_MCLASS_DESC                 109
#define IDS_MARRAY_DESC                 110
#define IDS_MMAPPING_DESC               111
#define IDS_NUMBER_DESC                 112
#define IDS_MAIN_WIN_VERSION            113
#define IDS_MAIN_CANNOT_RUN             114
#define IDS_MAIN_NO_TCPIP               115
#define IDS_MAIN_ERROR                  116
#define IDS_MAIN_NO_INI                 117
#define IDS_MAIN_NO_CFG                 118
#define IDS_MAIN_BAD_CFG                119
#define IDS_MAIN_SUCCESS                120
#define IDS_MAIN_MENU_ABOUT             121
#define IDS_MAIN_MENU_RESTART           122
#define IDS_MAIN_MENU_SHUTDOWN          123
#define IDS_MAIN_ABOUT                  124
#define IDS_MAIN_FIRST_RUN              125
#define IDS_MAIN_DLG_END                126
#define IDS_MAIN_USAGE                  127
#define IDS_MAIN_REG_SERVICE            128
#define IDS_MAIN_UNREG_SERVICE          129
#define IDS_MAIN_MENU_SETUP             130
#define IDR_MUDOS                       201
#define IDR_FUNCTION                    202
#define IDR_VALUE                       203
#define IDC_CFG_PATH                    1002
#define IDC_BROWSER                     1003
#define IDC_ADDR_PORT                   1004
#define IDC_HEART_BEAT                  1005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
